### ISSUE TITLE
Como adicionar uma variável de ambiente?

### ISSUE THREAD

**Issue by felipecrs** [discloud/docs#29]
Para fazer a conexão com o MongoDB, é necessário usar a string de conexão, que é um valor secreto e não deve ficar commitado no repositório do GitHub.

Para contornar isso, o jeito certo é usar variáveis de ambiente, e ter uma forma de definir elas no Discloud.

Não sei se essa função existe ou não, mas não encontrei nada na documentação.

Alguma ideia?

**Comment by MrGamingBR** [comment]
Usa JavaScript ?

**Comment by felipecrs** [comment]
Sim!

**Comment by MrGamingBR** [comment]
https://media.discordapp.net/attachments/801250240912424999/801260869480087562/unknown.png?width=669&height=419
Siga os passos acima

**Comment by JoaoOtavioS** [comment]
Olá felipecrs, tudo bem? pelo que vi sua dúvida já foi solucionada, peço que da próxima vez tire sua dúvida em nosso discord nos canais comunitários.
