### ISSUE TITLE
Sem suporte para bots feitos com a biblioteca DSharp

### ISSUE THREAD

**Issue by DroneN1456** [discloud/docs#32]
Favor colocar suporte ai familia, quero hospedar meu lindo bot

**Comment by JoaoOtavioS** [comment]
Olá DroneN1456, infelizmente no momento suportamos somente javascript, python e java, porém gostaria de lhe dar uma boa noticia, em nosso próprio website (https://discloudbot.com/) é possível visualizar que futuramente, teremos suporte pra Go, Ruby e C#
